#!/bin/bash

#PBS -l nodes=1:ppn=10
#PBS -l vmem=20gb
#PBS -l walltime=10:00:00
#PBS -N life

set -e
set -x

if [ `which singularity` ]
then
    echo "running via singularity"
    export MAXMEM=19000000
    time singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
else
    echo "running native matlab"
    module load matlab ccm
    export MATLABPATH=$MATLABPATH:$PWD
    export MAXMEM=19000000

    if [ `which ccmrun` ]
    then
        echo "running matlab via ccmrun - on bigred2"
        time ccmrun matlab -nodisplay -nosplash -r main
    else
        echo "running matlab"
        time matlab -nodisplay -nosplash -r main
    fi
fi

#make sure output_fe.mat exists
if [ ! -s output_fe.mat ];
then
	echo "output_fe.mat missing"
	exit 1
fi


